<a href="https://colab.research.google.com/github/rajan-dhinoja/python_libraries/blob/main/numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([3, 45 ,6, 70])

In [ ]:
myarr

array([ 3, 45,  6, 70])

In [ ]:
# here in below cells, np.int describes the bit of a number in array
myarr = np.array([3, 45,6, 70], np.int8)

In [ ]:
myarr

array([ 3, 45,  6, 70], dtype=int8)

In [ ]:
myarr2 = np.array([3, 45555555,6, 70], np.int32)

In [ ]:
myarr2

array([       3, 45555555,        6,       70], dtype=int32)

In [ ]:
my2darr = np.array([[3, 45 ,6, 70]])

In [ ]:
my2darr

array([[ 3, 45,  6, 70]])

In [ ]:
my2darr[0]

array([ 3, 45,  6, 70])

In [ ]:
my2darr[0, 1]

np.int64(45)

In [ ]:
myarr.shape

(4,)

In [ ]:
my2darr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int8')

In [ ]:
my2darr.dtype

dtype('int64')

In [ ]:
my2darr[0, 1] = 65

In [ ]:
my2darr

array([[ 3, 65,  6, 70]])

In [ ]:
# It gives dtype as object
np.array({34, 45, 56})

array({56, 34, 45}, dtype=object)

In [ ]:
# It gives an array of all Zeros
zeros = np.zeros((2, 4))

In [ ]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zeros.size

8

In [ ]:
# It gives the array of number starting from 0 to n-1
rng = np.arange(15)

In [ ]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# It creates an array of values from 1 to n, with count(number of values in a set).
#It will form the array in which the distance between each consecutive value will remain the same.
lspace = np.linspace(1, 50, 15)

In [ ]:
lspace

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

In [ ]:
lspace2 = np.linspace(1, 20, 10)

In [ ]:
lspace2

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
lspace3 = np.linspace(1,5,5)

In [ ]:
lspace3

array([1., 2., 3., 4., 5.])

In [ ]:
# Gives array of random elements
emp = np.empty((4,6))

In [ ]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.15710427e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
        9.34608432e-307, 7.56599128e-307, 1.60218491e-306]])

In [ ]:
# It creates an empty array of the same size as the previously created array, It will help to perform any operation in a newly created array.
empLike = np.empty_like(lspace)

In [ ]:
empLike

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

In [ ]:
empLike2 = np.empty_like(lspace3)

In [ ]:
empLike2

array([1., 2., 3., 4., 5.])

In [ ]:
# It Gives the identity matrix like Array
iden = np.identity(4)

In [ ]:
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr99 = np.arange(99)

In [ ]:
arr99

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
# It reshapes the complete array and divides into equal parts
arr99.reshape(9, 11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [ ]:
reshparr99 = arr99.reshape(3, 33)

In [ ]:
reshparr99

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
# It converts the array back to its original form.
reshparr99.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
reshparr99

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
reshparr99.shape

(3, 33)

In [ ]:
arr99

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr99.shape

(99,)

### 1D Array:-

In [ ]:
arr1d = np.array([ 2, 345, 421, 3, 20])

In [ ]:
# It gives the index at which the maximum element is there.
arr1d.argmax()

np.int64(2)

In [ ]:
# It gives the index at which the minimum element is there.
arr1d.argmin()

np.int64(0)

In [ ]:
# It gives the array of index where the value is the sequence of the elements.
arr1d.argsort()

array([0, 3, 4, 1, 2])

### 2D Array:-

In [ ]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# It gives the sum of all the elements in a Column(which means it is a Y-Axis).
arr2d.sum(axis=0)

array([12, 15, 18])

In [ ]:
# It gives the sum of all the elements in a Row(which means it is an X-Axis).
arr2d.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
arr2d.argmax()

np.int64(8)

In [ ]:
arr2d.argmin()

np.int64(0)

In [ ]:
arr2d.argmax(axis=0)

array([2, 2, 2])

In [ ]:
arr2d.argmax(axis=1)

array([2, 2, 2])

In [ ]:
arr2d.argmin(axis=0)

array([0, 0, 0])

In [ ]:
arr2d.argmin(axis=1)

array([0, 0, 0])

In [ ]:
arr2d.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
arr2d.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
arr2d.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
arr2d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
#It Transposes the array(which means Rows become Columns & Columns become Rows).
Tparr2d = arr2d.T

In [ ]:
Tparr2d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
Tparr2d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr2d.flat

In [ ]:
for item in arr2d.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [ ]:
for item in arr2d.flatten():
    print(item)

1
2
3
4
5
6
7
8
9


In [ ]:
# Prints all the elements in C Order(Row-Wise).
for x in np.nditer(arr2d, order='C'):
    print(x)

1
2
3
4
5
6
7
8
9


In [ ]:
# Prints all the elements in Fortan Order(Column-Wise).
for x in np.nditer(arr2d, order='F'):
    print(x)

1
4
7
2
5
8
3
6
9


In [ ]:
for item in Tparr2d.flat:
    print(item)

1
4
7
2
5
8
3
6
9


In [ ]:
# IT displays the number of dimensions of Array.
arr2d.ndim

2

In [ ]:
# Display the no. of elements
arr2d.size

9

In [ ]:
# Display the byte the array consumes.
arr2d.nbytes

72

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d2 = np.array([[9,8,7], [6,5,4], [3,2,1]])

In [ ]:
arr2d2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
# Displays the maximun element
arr2d2.max()

np.int64(9)

In [ ]:
# Displays the minimum element
arr2d.min()

np.int64(1)

In [ ]:
# It displays the index where the element is greater than 5.
np.where(arr2d > 5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [ ]:
np.count_nonzero(arr2d2)

9

In [ ]:
np.nonzero(arr2d2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [ ]:
arr2d2[1,0] = 0

In [ ]:
np.nonzero(arr2d2)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 1, 2, 0, 1, 2]))

In [ ]:
# NUMPY helps you to perform all the operations where lists cannot.
arr2d + arr2d2

array([[10, 10, 10],
       [ 4, 10, 10],
       [10, 10, 10]])

In [ ]:
arr2d * arr2d2

array([[ 9, 16, 21],
       [ 0, 25, 24],
       [21, 16,  9]])

In [ ]:
# list cannot perform such an operation. It concatenates the lists.
[34, 54] + [23, 43]

[34, 54, 23, 43]

In [ ]:
np.sqrt(arr1d)

array([ 1.41421356, 18.57417562, 20.51828453,  1.73205081,  4.47213595])

In [ ]:
np.sqrt(arr2d)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
np.sqrt(arr2d2)

array([[3.        , 2.82842712, 2.64575131],
       [0.        , 2.23606798, 2.        ],
       [1.73205081, 1.41421356, 1.        ]])

### How Numpy occupies less space than Python

In [ ]:
import sys

In [ ]:
py_arr = [1,2,3,4,5]

In [ ]:
np_arr = np.array(py_arr)

In [ ]:
print(sys.getsizeof(1))
print(len(py_arr))
sys.getsizeof(1) * len(py_arr)

28
5


140

In [ ]:
print(np_arr.itemsize)
print(np_arr.size)
np_arr.itemsize * np_arr.size

8
5


40